### ISSUE TITLE
Exception whenever the file is changed

### ISSUE THREAD

**Issue by jmanuel1** [AtomLinter/linter-flake8#103]
Whenever I make an edit to the file buffer, I get the following exception:

    Error: Traceback (most recent call last):
      File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Python34\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Python34\Scripts\flake8.exe\__main__.py", line 9, in <module>
      File "C:\Python34\lib\site-packages\flake8\main.py", line 33, in main
        report = flake8_style.check_files()
      File "C:\Python34\lib\site-packages\pep8.py", line 1832, in check_files
        runner(path)
      File "C:\Python34\lib\site-packages\flake8\engine.py", line 95, in input_file
        return fchecker.check_all(expected=expected, line_offset=line_offset)
      File "C:\Python34\lib\site-packages\pep8.py", line 1564, in check_all
        self.check_ast()
      File "C:\Python34\lib\site-packages\pep8.py", line 1511, in check_ast
        for lineno, offset, text, check in checker.run():
      File "C:\Python34\lib\site-packages\flake8_pep257.py", line 94, in run
        filename, source = load_file(self.filename)
      File "C:\Python34\lib\site-packages\flake8_pep257.py", line 29, in load_file
        return 'stdin', pep8.stdin_get_value()
      File "C:\Python34\lib\site-packages\pep8.py", line 1198, in stdin_get_value
        return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
    ValueError: I/O operation on closed file
      at exit (C:\Users\jason\.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.coffee:32:24)
      at triggerExitCallback (C:\Users\jason\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
      at ChildProcess.<anonymous> (C:\Users\jason\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

This is on Atom 1.0.19 (Windows 10). Flake8 is working properly on the command line.
Output of `flake8 --version`: `2.4.1 (pep8: 1.6.2, pyflakes: 0.8.1, flake8-pep257: 1.0.3, mccabe: 0.3.1) CPython 3.4.1 on Windows`. `pep257` is at version 0.5.0.

**Comment by Arcanemagus** [comment]
This is unfortunately an error with `flake8-pep257` (https://github.com/Robpol86/flake8-pep257/issues/2), you can try the alternative `flake8-docstrings` which should accomplish the same thing.
