### ISSUE TITLE
Error when adding a multiline docstring in existing class

### ISSUE THREAD

**Issue by rewritten** [AtomLinter/linter-flake8#131]
If one is adding a multiline docstring in an existing class (probably with unindented code after) a number of error screens appear. Here is a screenshot of what happens (I'm adding the docstring to the `First` class).

![atom-error](https://cloud.githubusercontent.com/assets/476895/11893376/80027b64-a570-11e5-947b-29c32ead387b.png)

Here is the traceback of the js execution thread (with the python exception on top):
```
Error: Traceback (most recent call last):
  File "/Users/saverio/.virtualenvs/---/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/flake8/engine.py", line 180, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/flake8/engine.py", line 171, in _retry_serial
    return func(*args, **kwargs)
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/flake8/engine.py", line 125, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/pep8.py", line 1456, in check_all
    self.check_logical()
  File "/Users/saverio/.virtualenvs/---/lib/python2.7/site-packages/pep8.py", line 1328, in check_logical
    (start_row, start_col) = mapping[0][1]
TypeError: 'NoneType' object has no attribute '__getitem__'
    at parameters.exit (/Users/saverio/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.js:74:20)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.1.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /opt/homebrew-cask/Caskroom/atom/1.1.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.1.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I understand that the pep8 python package might be the cause of the failure, but if it's an "expected" failure, could it be just catched and swallowed?

**Comment by rewritten** [comment]
The problem is that the error popup must be closed manually, so it interrupts the coding flow...

**Comment by rewritten** [comment]
for what it's worth, this is the output of `apm list`:
```
Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.23.0
├── autocomplete-snippets@1.8.0
├── autoflow@0.26.0
├── autosave@0.23.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.0.0
├── base16-tomorrow-light-theme@1.0.0
├── bookmarks@0.38.0
├── bracket-matcher@0.79.0
├── command-palette@0.37.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.194.0
├── fuzzy-finder@0.93.0
├── git-diff@0.57.0
├── go-to-line@0.30.0
├── grammar-selector@0.48.0
├── image-view@0.56.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.49.0
├── language-clojure@0.18.0
├── language-coffee-script@0.45.0
├── language-csharp@0.11.0
├── language-css@0.35.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.40.0
├── language-html@0.42.0
├── language-hyperlink@0.15.0
├── language-java@0.16.1
├── language-javascript@0.100.0
├── language-json@0.17.1
├── language-less@0.28.3
├── language-make@0.20.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.0
├── language-perl@0.31.0
├── language-php@0.34.0
├── language-property-list@0.8.0
├── language-python@0.41.0
├── language-ruby@0.62.0
├── language-ruby-on-rails@0.24.0
├── language-sass@0.43.0
├── language-shellscript@0.20.0
├── language-source@0.9.0
├── language-sql@0.19.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.34.0
├── language-yaml@0.24.0
├── line-ending-selector@0.3.0
├── link@0.31.0
├── markdown-preview@0.156.1
├── metrics@0.53.0
├── notifications@0.62.1
├── one-dark-syntax@1.1.1
├── one-dark-ui@1.1.5
├── one-light-syntax@1.1.1
├── one-light-ui@1.1.5
├── open-on-github@0.40.0
├── package-generator@0.41.0
├── release-notes@0.53.0
├── settings-view@0.232.0
├── snippets@1.0.1
├── solarized-dark-syntax@0.39.0
├── solarized-light-syntax@0.23.0
├── spell-check@0.63.0
├── status-bar@0.80.0
├── styleguide@0.45.0
├── symbols-view@0.110.1
├── tabs@0.88.0
├── timecop@0.33.0
├── tree-view@0.198.0
├── update-package-dependencies@0.10.0
├── welcome@0.32.0
├── whitespace@0.32.0
└── wrap-guide@0.38.1

/Users/saverio/.atom/packages (21)
├── Zen@0.16.3
├── atom-beautify@0.28.19
├── atom-django@0.3.2
├── autocomplete-python@1.2.3
├── autoprefixer@3.1.0
├── coffee-compile@0.20.1
├── django-templates@0.5.0
├── language-crontab@0.1.0
├── language-ember-script@0.2.0
├── language-gettext@0.6.1
├── language-haml@0.23.13
├── language-ini@1.14.0
├── language-nginx@0.6.1
├── language-slim@0.5.0
├── linter@1.11.3
├── linter-flake8@1.9.3
├── minimap@4.18.2
├── pigments@0.19.3
├── python-autopep8@0.1.3
├── python-tools@0.6.7
└── sort-lines@0.12.0
```

**Comment by Arcanemagus** [comment]
Do you get the same error running `flake8` from the command line? That looks like a bug from there rather than the `linter-flake8` package.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response, if you find that this isn't an issue with `flake8` (or more specifically a plugin for it), do let us know.

**Comment by rewritten** [comment]
Whoa sorry I completely missed the first response. Indeed the `flake8` command line shows the same behavior, I'll file it there.

**Comment by Arcanemagus** [comment]
Before filing an issue make sure you didn't accidentally update `pep8` past v1.5.7, I'm almost positive that's the stack trace you get if you do since things are pretty broken past that. (Fixed in the next release, but they haven't released it yet for some reason)

**Comment by rewritten** [comment]
I'm on `pep8==1.5.7` (as per flake8 2.5.1 requirements: `pep8 (>=1.5.7,!=1.6.0,!=1.6.1,!=1.6.2)`).

**Comment by rewritten** [comment]
The issue is already open since october: https://github.com/PyCQA/pep8/issues/454  Thanks for your help for getting into the right path and sorry for the noise.

**Comment by Arcanemagus** [comment]
No problem and thanks for pointing to the right issue!
