### ISSUE TITLE
BufferedProcessError: Failed to spawn command 'flake8'- nothing I've tried has helped.

### ISSUE THREAD

**Issue by magicguy38** [AtomLinter/linter-flake8#149]
I recently installed Atom and I am fairly new to coding in general. I installed flake8, the base linter(version 1.11.3), and the flake8 linter (version 1.10.0). I've reinstalled all the plugins, Python, and Atom (version 1.43)  twice. Whenever I take any sort of action this error appears:

```
BufferedProcessError: Failed to spawn command 'flake8'. Make sure it's a file, not a directory, and it's executable.
    at handleError (C:\Users\Magicguy38\.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:67:26)
    at parameters.exit (C:\Users\Magicguy38\.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:86:13)
    at triggerExitCallback (C:\Users\Magicguy38\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Magicguy38\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

I'm not getting any sort of linting whilst attempting to program, and I can't find anyone who's had this problem through google. Any help would be appreciated!

**Comment by Arcanemagus** [comment]
If you run `where.exe flake8` what is the output?

**Comment by magicguy38** [comment]
Would I run where.exe just for C:\Users\?

**Comment by magicguy38** [comment]
But if you just want to know the location of flake8.exe, it is located in \Python\Python35-32\Scripts

**Comment by Arcanemagus** [comment]
`where.exe flake8` (regardless of where you run it) would return where Windows would resolve a call to `flake8` to, the error you posted above is due to Atom being unable to find `flake8`, which should only happen if the location `flake8` is installed to isn't in the path.

If you put `C:\Python\Python35-32\Scripts\flake8.exe` into the `Executable Path` setting, do you stop getting that error?

**Comment by magicguy38** [comment]
That fixed it, thank you!
