### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by timc13** [AtomLinter/linter-flake8#183]
I'm getting this error now and nothing is linting on Atom 1.7.0

**Comment by timc13** [comment]
hopefully, this helps?
```
Uncaught Error: write EPIPE
exports._errnoException @ util.js:856
exports._exceptionWithHostPort @ util.js:879
afterWrite @ net.js:763

events.js:141 Uncaught Error: write EPIPE
```

**Comment by Arcanemagus** [comment]
What OS are you on? Did this start with Atom v1.7.0? Does v1.6.2 work?

**Comment by timc13** [comment]
I'm on OSX El Capitan.  I'm not sure at what point in the auto-upgrade history it broke, but I believe 1.6.2 did work.

**Comment by timc13** [comment]
The latest release of Atom now logs an exception before that EPIPE error.  Perhaps this can shed some light on this issue?

```
Error reporting uncaught exception Error: Cannot find module '../package.json'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/exception-reporting/lib/reporter.js:14:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/exception-reporting/lib/reporter.js:209:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/exception-reporting/lib/main.js:19:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:832:32```

**Comment by Arcanemagus** [comment]
Can you try the latest release (v1.13.3) and see if you are still experiencing issues?

**Comment by timc13** [comment]
this issue seems fixed...not sure which Atom update did it.

**Comment by MichaelrMentele** [comment]
I'm using the latest version of atom for osx and I'm having this issue. 
![image](https://user-images.githubusercontent.com/9519712/31681156-3f94b036-b32b-11e7-9b0f-6b645e2d14af.png)

**Comment by MichaelrMentele** [comment]
Flake8 works for Atom on my linux box running Ubuntu but for some reason just times out on my mac.

**Comment by Arcanemagus** [comment]
@MichaelrMentele That has _nothing_ to do with this issue, please see some of the recent issues for other reports of users having issues on macOS.
