### ISSUE TITLE
Error: spawn flake8 ENOENT

### ISSUE THREAD

**Issue by quijote108** [AtomLinter/linter-flake8#197]
I have the following error:

Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)

It seems it's something with node.js but i don't know what.

**Comment by quijote108** [comment]
I resolve the problem reinstalling with pip.
