### ISSUE TITLE
Error: spawn flake8 ENOENT

### ISSUE THREAD

**Issue by thjoshi** [AtomLinter/linter-flake8#231]
Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Just updated to 1.9.6 on atom and now get these pop ups consistently.  
Checked flake8 runs, updated, etc...

**Comment by thjoshi** [comment]
Resolved with executablePath in config.cson

**Comment by veehz** [comment]
@thjoshi Can you help me?
I have this problem too..

Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Thanks.

**Comment by Arcanemagus** [comment]
@veehz you need to ensure that `flake8` is available in your `$PATH`. You can force it to work by putting the output of `which flake8` (*NIX) or `where.exe flake8` (Windows) in the "Executable Path" setting.

**Comment by Tomatoesp** [comment]
pip3 install flake8

**Comment by davincif** [comment]
For me, I solved the problem with:
```console
sudo pip3 install flake8
sudo pip3 install setuptools
```

**Comment by haroldao** [comment]
> For me, I solved the problem with:
> 
> ```
> sudo pip3 install flake8
> sudo pip3 install setuptools
> ```

Thanks man. It worked. 🤜🏽
