### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Dan9er** [AtomLinter/linter-flake8#248]
Atom Version: 1.0.11 (32-bit)
System (`uname -a`): Linux AcerNotebook 3.2.0-109-generic-pae #150-Ubuntu SMP Fri Aug 12 18:59:00 UTC 2016 i686 i686 i386 GNU/Linux

### **Error:**
```
TypeError: undefined is not a function
    at validate (/home/dan9er/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/helpers.js:77:24)
    at Object.<anonymous> (/home/dan9er/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:8:41)
    at GeneratorFunctionPrototype.next (native)
    at step (/home/dan9er/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:100:191)
    at /home/dan9er/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:100:451
    at Object.<anonymous> (/home/dan9er/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:100:99)
    at Object.exec (/home/dan9er/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:92:17)
    at Object.provider.lint (/home/dan9er/.atom/packages/linter-flake8/lib/main.coffee:234:24)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/dan9er/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/dan9er/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/dan9er/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/dan9er/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /home/dan9er/.atom/packages/linter/lib/editor-linter.js:86:22
    at /home/dan9er/.atom/packages/linter/lib/helpers.coffee:25:18
```
### **Config:**
```coffeescript
"*":
  welcome:
    showOnStartup: false
  core:
    audioBeep: false
  editor:
    invisibles: {}
    tabLength: 4
  minimap:
    plugins:
      "find-and-replace": true
      "find-and-replaceDecorationsZIndex": 0
      cursorline: true
      cursorlineDecorationsZIndex: 0
```

### Packages
```
Built-in Atom packages (88)
├── about@1.1.0
├── archive-view@0.60.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.10.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.19.0
├── autocomplete-snippets@1.7.1
├── autoflow@0.25.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@0.27.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.36.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.21.0
├── find-and-replace@0.180.0
├── fuzzy-finder@0.88.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.1
├── keybinding-resolver@0.33.0
├── language-c@0.47.1
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.7.0
├── language-css@0.33.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.37.0
├── language-html@0.41.2
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.92.0
├── language-json@0.16.0
├── language-less@0.28.2
├── language-make@0.17.0
├── language-mustache@0.12.0
├── language-objective-c@0.15.0
├── language-perl@0.28.0
├── language-php@0.29.0
├── language-property-list@0.8.0
├── language-python@0.39.0
├── language-ruby@0.57.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.40.1
├── language-shellscript@0.15.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.32.0
├── language-yaml@0.24.0
├── line-ending-selector@0.0.5
├── link@0.30.0
├── markdown-preview@0.150.0
├── notifications@0.59.0
├── one-dark-syntax@1.1.0
├── one-dark-ui@1.0.3
├── one-light-syntax@1.1.0
├── one-light-ui@1.0.3
├── open-on-github@0.38.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.216.0
├── snippets@0.95.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.59.0
├── status-bar@0.79.0
├── styleguide@0.44.0
├── symbols-view@0.104.0
├── tabs@0.84.0
├── timecop@0.31.0
├── tree-view@0.186.0
├── update-package-dependencies@0.10.0
├── welcome@0.30.0
├── whitespace@0.31.0
└── wrap-guide@0.35.0

/home/dan9er/.atom/packages (5)
├── linter@1.11.16
├── linter-flake8@1.13.4
├── minimap@4.24.7
├── minimap-cursorline@0.2.0
└── minimap-find-and-replace@4.5.1
```

**Comment by Arcanemagus** [comment]
Your Atom version is _very very_ old, in this case too old for `Object.assign` to exist. Update to the current stable version and it should work fine for you.

Thanks to @steelbrain for catching where this was failing 😉.

**Comment by Dan9er** [comment]
@Arcanemagus Is there any way to get the latest stable **32-bit** build? If so, how to uninstall the old version?

**Comment by Arcanemagus** [comment]
Looks like you can use this unofficial repo here: https://launchpad.net/~webupd8team/+archive/ubuntu/atom

Or build it yourself, but that can be more involved.
