### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ma55acre** [AtomLinter/linter-flake8#259]
i don't know what happen, i had never programed to the atom. help please.
```
Error: spawn flake8 ENOENT
Error: spawn flake8 ENOENT
    at getENOENTError (C:\Users\Emma\.atom\packages\linter-flake8\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\Emma\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by Arcanemagus** [comment]
Do you have `flake8` installed on your system? Either you should get back a path from `where.exe flake8` when you run that in powershell / command prompt, or you need to put the full path of `flake8` into the "Executable Path" setting.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response, if you are still having a problem getting this working feel free to respond further and re-open this!
