### ISSUE TITLE
Error: spawn flake8 ENOENT (linter-flake8 2.0.2 on atom 1.11.2)

### ISSUE THREAD

**Issue by nickbooties** [AtomLinter/linter-flake8#263]
```
Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
Do you have `flake8` installed on your system?

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response. If you are still having a problem getting this working feel free to comment further and we can try to figure out what is wrong!
