### ISSUE TITLE
Doesn’t work any more with atom 0.190.0

### ISSUE THREAD

**Issue by andya9** [AtomLinter/linter-flake8#27]
The package doesn’t do any lint anymore (I don’t think it’s an issue of the main linter package, because i.e. linter-tidy still works).

How to replicate: just open a python file, then try messing its syntax; nothing happens.

**Comment by andya9** [comment]
More info from atom notifications:

**Atom Version**: 0.190.0
**System**: linux 3.19.3-1-ARCH
**Thrown From**: [linter-flake8](https://github.com/AtomLinter/linter-flake8) package, v1.3.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /data/linux/configs/atom/packages/linter-flake8/lib/linter-flake8.coffee:40

TypeError: undefined is not a function
  at LinterFlake8.destroy (/data/linux/configs/atom/packages/linter-flake8/lib/linter-flake8.coffee:40:17)
  at LinterView.remove (/data/linux/configs/atom/packages/linter/lib/linter-view.coffee:247:7)
  at /data/linux/configs/atom/packages/linter/lib/linter-view.coffee:119:8
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app/src/text-editor.js:281:27)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:423:18)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app/src/pane.js:398:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:582:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app/src/workspace.js:621:21)
  at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app/src/workspace-element.js:307:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:242:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:180:20)

```

**Comment by badray** [comment]
@andya9 thx for investigation, after work I'll try to debug it. This also will be a motivation for me to release new version with the changes that are waiting for it :P.

**Comment by andya9** [comment]
Thank’you @badray 
I tried now to uninstall and reinstall, but nothing changed.

**Comment by andya9** [comment]
I reinstalled the python modules too, and now it suddenly works again; I can’t understand what happened, but it seems it wasn’t related to the package itself. =)

**Comment by badray** [comment]
@andya9 happy to hear that I was debugging it, and stack trace was making no sense to me :+1:

**Comment by andya9** [comment]
I’m sorry that I caused problems; thank’you for working on this
