### ISSUE TITLE
"Given editor is not really an editor" after upgrade to Atom  1.12

### ISSUE THREAD

**Issue by ludwiktrammer** [AtomLinter/linter-flake8#273]
After I updated to Atom 1.12 when editing Python files I get constant red tooltips saying:

```
Error: linter-flake8:: Invalid point encountered! See console for details.
Error: linter-flake8:: Invalid point encountered! See console for details.
    at Error (native)
    at extractRange (/Users/ludwik/.atom/packages/linter-flake8/lib/main.js:73:11)
    at Object.<anonymous> (/Users/ludwik/.atom/packages/linter-flake8/lib/main.js:221:25)
    at next (<anonymous>)
    at step (/Users/ludwik/.atom/packages/linter-flake8/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

In console I get those errors:

```
message-registry.js [sm]:41Uncaught (in promise) Error: Given editor is not really an editor
    at MessageRegistry.set (/Users/ludwik/.atom/packages/linter/lib/message-registry.js:41:15)
    at /Users/ludwik/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/ludwik/.atom/packages/linter/lib/linter-registry.js:66:26
```

and

```
main.js [sm]:65linter-flake8:: Invalid point encountered in the attached message ObjectextractRange @ main.js [sm]:65
main.js [sm]:65linter-flake8:: Invalid point encountered in the attached message ObjectextractRange @ main.js [sm]:65
```
![screen shot 2016-11-11 at 16 15 04](https://cloud.githubusercontent.com/assets/5337669/20219611/85bed242-a82a-11e6-81cf-4c7429c5591f.png)

Tested in Atom 1.12.1 on Mac OS X 10.11.6

**Comment by Arcanemagus** [comment]
If you expand the `> Object` part of the message it will give you details on what the original message that had an invalid point was. Without that I can't say for sure what your issue is. It's likely that you are hitting #270 or something similar though.

**Comment by ludwiktrammer** [comment]
The errors gotten less frequent, but are still happening every couple of minutes. Here is a screenshot with Object expanded:

![screen shot 2016-11-17 at 12 02 14](https://cloud.githubusercontent.com/assets/5337669/20386883/d609bca2-acbd-11e6-8613-73086e84a0e5.png)
