### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by paltman** [AtomLinter/linter-flake8#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-flake8](https://github.com/AtomLinter/linter-flake8) package, v1.4.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/paltman/.atom/packages/linter-flake8/lib/linter-flake8.coffee:51

TypeError: undefined is not a function
  at LinterFlake8.destroy (/Users/paltman/.atom/packages/linter-flake8/lib/linter-flake8.coffee:51:17)
  at LinterView.remove (/Users/paltman/.atom/packages/linter/lib/linter-view.coffee:252:7)
  at /Users/paltman/.atom/packages/linter/lib/linter-view.coffee:124:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:279:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:444:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:582:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:621:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:307:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
  2x -1:19.2.0 core:backspace (atom-text-editor#linter-flake8.executableDir.editor.mini)
  5x -0:50.4.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:48.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:44.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:37.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:26.8.0 core:save (atom-text-editor.editor)
  5x -0:19.7.0 core:backspace (atom-text-editor.editor)
     -0:18.7.0 core:save (atom-text-editor.editor)
     -0:17.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:05.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/paltman/Development",
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "Thumbs.db",
      "*.pyc"
    ]
  },
  "linter-flake8": {
    "executableDir": "/usr/local/opt/pyenv/shims/"
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.1
linter-flake8, v1.4.0
trailing-spaces, v0.2.5

# Dev
No dev packages
```

**Comment by badray** [comment]
Hi, thanks for reporting - I'll have to fix it before **June 1st** :)

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/AtomLinter/linter-flake8/pull/38
