### ISSUE TITLE
Error: spawn flake8 ENOENT

### ISSUE THREAD

**Issue by Spitfire1900** [AtomLinter/linter-flake8#313]
The following error appears when opening a new python file (username is commented out):

```
Error: spawn flake8 ENOENT
    at getENOENTError (C:\Users\<username>\.atom\packages\linter-flake8\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\<username>\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by Spitfire1900** [comment]
This error appears when flake8 is not installed.

`pip install flake8`
