### ISSUE TITLE
Error: spawn flake8 ENOENT with Flake8 installed in virtualenv

### ISSUE THREAD

**Issue by BobAalsma** [AtomLinter/linter-flake8#342]
```
Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Installed in the environment are
flake8 (2.5.5)
flake8-docstrings (1.0.3)
flake8-polyfill (1.0.1)
pyflakes (0.8.1)

Newbie: what else should I tell you?

**Comment by BobAalsma** [comment]
Error disappeared after filling Executable Path with the full path to flake8, so /Users/....

I think I assumed that $PATH would be used, sorry

**Comment by Arcanemagus** [comment]
`$PATH` is only used when you launch Atom from that environment, to work properly in a virtualenv you would need to close _all_ Atom windows, then launch from within the virtualenv by running `atom .`.
