### ISSUE TITLE
Failed to activate the linter-flake8 package

### ISSUE THREAD

**Issue by tran-david** [AtomLinter/linter-flake8#371]
`Error parsing /Users/David/.atom/packages/linter-flake8/node_modules/sb-promisify/package.json: Unexpected token } in JSON at position 3010`

```
SyntaxError: Error parsing /Users/David/.atom/packages/linter-flake8/node_modules/sb-promisify/package.json: Unexpected token } in JSON at position 3010
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:172:20)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/David/.atom/packages/linter-flake8/node_modules/sb-npm-path/lib/helpers.js:51:20)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/David/.atom/packages/linter-flake8/node_modules/sb-npm-path/lib/index.js:28:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/David/.atom/packages/linter-flake8/node_modules/sb-exec/lib/helpers.js:67:18)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
```

This was originally working for me, but after updating the package I now get this error. Any ideas?

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? The `package.json` for that dependency only has 925 characters so it's pretty hard for it to be giving an error at position 3010 without something being _very_ wrong.

**Comment by tran-david** [comment]
Oh weird, but that reinstalling it worked! Yeah by running apm install linter-flake8, this fixed it. I guess by using the GUI to update packages under the atom packages page, this might have caused issues. Thanks!

**Comment by Arcanemagus** [comment]
That normally works just fine, there seems to be a very rare (~1/20000) chance that it fails to install dependencies properly though.
