### ISSUE TITLE
Flake8 Constantly Crashing

### ISSUE THREAD

**Issue by jadchaar** [AtomLinter/linter-flake8#417]
I used Flake8 without any issues a month ago, but I recently began using Atom to do some Python development again. I am getting constant error messages when opening Python files saying "Flake8 has crashed", with the following console output:

```
linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/Users/jadchaar/anaconda/bin/flake8", line 6, in <module>
    sys.exit(flake8.main.cli.main())
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/main/application.py", line 315, in _run
    self.initialize(argv)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/main/application.py", line 298, in initialize
    self.register_plugin_options()
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/main/application.py", line 154, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/plugins/manager.py", line 488, in register_options
    list(self.manager.map(register_and_enable))
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/plugins/manager.py", line 284, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/plugins/manager.py", line 484, in register_and_enable
    call_register_options(plugin)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/plugins/manager.py", line 380, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/plugins/manager.py", line 230, in register_options
    add_options(optmanager)
  File "/Users/jadchaar/anaconda/lib/python3.5/site-packages/flake8/_pyflakes.py", line 78, in add_options
    parser.config_options.extend(['builtins', 'doctests',
AttributeError: 'OptionManager' object has no attribute 'config_options'(anonymous function) @ /Users/jadchaar/.atom/packages/linter-flake8/lib/main.js:198
```

Would really appreciate some help. Thanks.

**Comment by Staberinde** [comment]
Looks like that's a problem with flake8 itself.

It seems like another occurance of this bug here: https://gitlab.com/pycqa/flake8/issues/281

**Comment by Arcanemagus** [comment]
Closing as there is nothing that can be done about it here.
