### ISSUE TITLE
import error no module named pycodestyle

### ISSUE THREAD

**Issue by FeralBytes** [AtomLinter/linter-flake8#419]
After updating linter-flake8 to 2.2.1 it started throwing errors and crashing all of the time. Even un-installed and re-installed.

```
main.js [sm]:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/usr/bin/flake8", line 9, in <module>
    load_entry_point('flake8==2.5.4', 'console_scripts', 'flake8')()
  File "/usr/lib/python3/dist-packages/flake8/main.py", line 25, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/usr/lib/python3/dist-packages/flake8/engine.py", line 233, in get_style_guide
    kwargs['parser'], options_hooks = get_parser()
  File "/usr/lib/python3/dist-packages/flake8/engine.py", line 74, in get_parser
    (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()
  File "/usr/lib/python3/dist-packages/flake8/engine.py", line 58, in _register_extensions
    checker = _load_entry_point(entry, verify_requirements=False)
  File "/usr/lib/python3/dist-packages/flake8/engine.py", line 37, in _load_entry_point
    plugin = entry_point.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/flake8_docstrings.py", line 9, in <module>
    import pycodestyle
ImportError: No module named 'pycodestyle'
(anonymous function) @ main.js [sm]:201
/usr/share/atom/resources/app.asar/src/config.js:680 'atom-beautify.yaml.padding' could not set the default. Attempted default: undefined; Schema: {"type":"integer","default":null,"minimum":0,"description":"The amount of padding to add next to each line. (Supported by align-yaml)","title":"Padding","beautifiers":["align-yaml"],"key":"padding","language":{"name":"YAML","namespace":"yaml"}}
```

Used pip to install pycodestyle and to update flake8; but still get error:

```
/home/wolfrage/.atom/packages/linter-flake8/lib/main.js:198 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flake8/plugins/manager.py", line 175, in load_plugin
    self._load(verify_requirements)
  File "/usr/local/lib/python3.5/dist-packages/flake8/plugins/manager.py", line 147, in _load
    self._plugin = resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/flake8_docstrings.py", line 21, in <module>
    class EnvironError(pep257.Error):
AttributeError: module 'pydocstyle' has no attribute 'Error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/dist-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/dist-packages/flake8/main/application.py", line 315, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.5/dist-packages/flake8/main/application.py", line 297, in initialize
    self.find_plugins()
  File "/usr/local/lib/python3.5/dist-packages/flake8/main/application.py", line 147, in find_plugins
    self.check_plugins.load_plugins()
  File "/usr/local/lib/python3.5/dist-packages/flake8/plugins/manager.py", line 392, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/usr/local/lib/python3.5/dist-packages/flake8/plugins/manager.py", line 284, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flake8/plugins/manager.py", line 390, in load_plugin
    return plugin.load_plugin()
  File "/usr/local/lib/python3.5/dist-packages/flake8/plugins/manager.py", line 183, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "D" due to module 'pydocstyle' has no attribute 'Error'.
```

**Comment by Arcanemagus** [comment]
Can you try uninstalling `flake8_docstrings`? It is known to currently be [broken](https://gitlab.com/pycqa/flake8-docstrings/issues/19), although none of your errors posted are the same stack trace.

**Comment by Arcanemagus** [comment]
`flake8-docstrings` has released a fixed version, can you update to that and try again?

**Comment by FeralBytes** [comment]
@Arcanemagus the update to flake8-docstrings has resolved the issue. Thank you.
