### ISSUE TITLE
Flake8 crashed! TypeError: unorderable types: str() > int()

### ISSUE THREAD

**Issue by keisuke-nakata** [AtomLinter/linter-flake8#451]
<img width="1680" alt="_2017-05-29_11_17_46" src="https://cloud.githubusercontent.com/assets/6150143/26534582/d26c62bc-4460-11e7-8e3c-d1ed3bef7874.png">

My linter-flake8 reports that Flake8 crashed:

```
main.js [sm]:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce3' in position 250: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/Users/keisuke.nakata/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: unorderable types: str() > int()
```

I found that linter-flake8 crashes when a file contains non-ascii characters (in my case, Japanese ones).
Executing flake8 from terminal works fine.

Thank you in advance!

**Comment by keisuke-nakata** [comment]
https://gitlab.com/pycqa/flake8/issues/321#note_28714561 solves my problem.
(Actually I set the environment variable `PYTHONIOENCODING` to `"utf8"`.)

This problem seems to be a flake8 one, but I could not understand why atom's flake8 cashes but original flake8 (from terminal) does not.

**Comment by ddaanet** [comment]
The lack of an encoding declaration in your python file might be part of the problem.

The difference of behaviour probably comes from how Atom have different environment variables than commands started from the terminal.

@lee-dohm gives some information on this issue and how to debug your environment, here: https://discuss.atom.io/t/os-x-environment-variables-not-set-e-g-gopath/32131

**Comment by Arcanemagus** [comment]
Note also that `flake8` currently ignores encodings for `stdin` input (which is how it is called here), this is fixed in their `master` branch but hasn't yet been released.

**Comment by sampeka** [comment]
Experiencing the same issue, was fine until a recent update. Is there a way to see the previous version I had?

**Comment by Arcanemagus** [comment]
@sampeka Flake8 versions can be found [here](https://flake8.readthedocs.io/en/latest/release-notes/index.html).

**Comment by phapdv** [comment]
@keisuke-nakata maybe can help you.
export to your shell.
```
export LANG='en_US.UTF-8'
export LC_CTYPE='UTF-8'
```
worked for me.

**Comment by Arcanemagus** [comment]
Marking this as closed as it seems it can be fixed with user configuration, and wasn't a bug in this package in the first place.
