### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'withDoctest

### ISSUE THREAD

**Issue by luisincrespo** [AtomLinter/linter-flake8#458]
Hey there, I keep getting this error when working with python files, anytime I make a change in the code:
<img width="417" alt="screen shot 2017-06-05 at 11 03 04 am" src="https://cloud.githubusercontent.com/assets/4452976/26789556/a69ca510-49de-11e7-94f3-506ebe573285.png">

Here's the traceback:
```
main.js [sm]:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/main/application.py", line 322, in run
    self._run(argv)
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/main/application.py", line 306, in _run
    self.run_checks()
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/main/application.py", line 244, in run_checks
    self.file_checker_manager.run()
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/checker.py", line 350, in run
    self.run_serial()
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/checker.py", line 334, in run_serial
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/checker.py", line 510, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/checker.py", line 464, in run_check
    return plugin['plugin'](**arguments)
  File "/Users/luiscrespo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flake8/plugins/pyflakes.py", line 74, in __init__
    withDoctest=with_doctest)
TypeError: __init__() got an unexpected keyword argument 'withDoctest'
```

**Comment by ddaanet** [comment]
Superficially, it looks like the pyflakes version is not compatible with the flake8 version.

Try upgrading pyflakes and flake8. And provide the versions of the packages are using.

In any case, it's a not a bug in `linter-flake8`, but in something in the python layer (which is called through the flake8 command).

**Comment by luisincrespo** [comment]
Thanks @ddaanet, and yep I upgraded `flake8` and the problem is gone. Closing this issue.
