### ISSUE TITLE
UNC Paths are not supported

### ISSUE THREAD

**Issue by Drabynoops** [AtomLinter/linter-flake8#481]
This is the full error message (edited for consieration):

```
Error: '\\<Network Drive>\<DirectoryOne>\<DirectoryTwo>'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
    at ChildProcess.<anonymous> (C:\Users\<user name>\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
It directs me to the except statement at line 192. I will take the time to look later, but if anyone happens to know and save me the time that would be great.

I do have another add on that adds a terminal Atom, but this started very recently as has not been an issue prior.

**Comment by acimmarusti** [comment]
This issue is definitely biting me right now. It's been open for >4 years, is there any solution? 
It's not a flake8 issue. it does have support for UNC paths.
This error message is typical when trying to set a UNC path as the current working directory.
The "solution" is to use the `pushd` / `popd` commands as seen in the SO link.
https://stackoverflow.com/questions/9013941/how-to-run-batch-file-from-network-share-without-unc-path-are-not-supported-me
