### ISSUE TITLE
linter-flake8 not working and no user feeback using Atom 1.0.0

### ISSUE THREAD

**Issue by JoeJasinski** [AtomLinter/linter-flake8#49]
I'm using Atom 1.0.0 and recently installed this plugin.  I've installed flake8 as recommended and it is located in /usr/bin/.  In the Atom linter-flake8 settings menu, I've set the Executable Dir to /usr/bin/.  I don't see any deprecation warnings or any indication that flake8 is not found.  I don't see any evidence that this plugin is functioning when I try to edit Python files.  I've tried restarting Atom.  Is there something I have to do to enable the plugin or is it automatic?  Is there a keyboard shortcut that I have to hit to get it to parse? Does this support Atom 1.0.0? 

I'm using Ubuntu 14.04.  Flake8 is installed and is found. 

    $ which flake8
    /usr/bin/flake8

Here is my config.  

    "*":
      "exception-reporting":
        userId: "***********************"
      welcome:
        showOnStartup: false
      core:
        disabledPackages: [
          "language-django"
        ]
      editor:
        invisibles: {}
        tabLength: 4
        showIndentGuide: true
      "linter-flake8":
        maxLineLength: 99
        executableDir: "/usr/bin/"
        selectErrors: [
          "E"
          "W"
        ]

The demo animation is exactly what I'm looking for in a linter for Atom, so this this plugin is very interesting to me.  I'm hoping it will work.  Thanks for reading.

**Comment by badray** [comment]
Hi @JoeJasinski. Obviously it support Atom 1.0.0. Could you paste output from the developers console? Have You installed https://github.com/AtomLinter/Linter? I dont see this base package in your config...

**Comment by vstoykov** [comment]
@JoeJasinski Did you edit Django files and have installed `atom-language-django`? If so you need to change syntax to `Python` instead of `Python Django`.

If this is your problem there is a fix for that in master branch but it's not released yet.

**Comment by badray** [comment]
@vstoykov I've released it seconds ago. Btw I also thought that may fix this particular problem.

**Comment by vstoykov** [comment]
Thanks @badray. I just installed this plugin on my home computer and it works like a charm (except for the fact that I needed to reinstall my system flake8, but this was problem on my installation. Nothing related to this plugin)

**Comment by JoeJasinski** [comment]
Thank you for your responses.  I think this comes down to user error on my part.  I had installed flake8-docstrings and flake8, but totally missed the part about needing the "linter" package (I must have thought linter and linter-flake8 were the same thing upon glancing at it).  Thank you @badray for putting my on the right track for this.  I've installed linter and linter-flake8 1.5.0 and it works like a charm.

**Comment by badray** [comment]
@JoeJasinski you're welcome :)

**Comment by MikeyBrat** [comment]
init.coffee? [sm]:6 activate linter-python-pyflakes
css Failed to load resource: net::ERR_FILE_NOT_FOUND
VM22 <embedded>:14 Unable to locate git workspace root for /mnt/home/Docs. Expected if /mnt/home/Docs is not in a git repository. GitError: git rev-parse --show-toplevel in /mnt/home/Docs exited with code 128
stdout: 
stderr: fatal: not a git repository (or any parent up to mount point /initrd/mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at new GitError (/initrd/mnt/dev_save/atom/atom-amd64.deb.extracted/usr/share/atom/resources/app/static/<embedded>:14:2765520)
    at Promise (/initrd/mnt/dev_save/atom/atom-amd64.deb.extracted/usr/share/atom/resources/app/static/<embedded>:14:2770338)
    at <anonymous>
revParse @ VM22 <embedded>:14
VM22 <embedded>:14 Unable to locate git workspace root for /mnt/home/Docs/Hithere.py. Expected if /mnt/home/Docs/Hithere.py is not in a git repository. GitError: git rev-parse --show-toplevel in /mnt/home/Docs exited with code 128
stdout: 
stderr: fatal: not a git repository (or any parent up to mount point /initrd/mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at new GitError (/initrd/mnt/dev_save/atom/atom-amd64.deb.extracted/usr/share/atom/resources/app/static/<embedded>:14:2765520)
    at Promise (/initrd/mnt/dev_save/atom/atom-amd64.deb.extracted/usr/share/atom/resources/app/static/<embedded>:14:2770338)
    at <anonymous>
revParse @ VM22 <embedded>:14
linter-registry.js? [sm]:137 [Linter] Error running Flake8 Error: Traceback (most recent call last):
  File "/usr/bin/flake8", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flake8==3.6.0' distribution was not found and is required by the application
    at ChildProcess.<anonymous> (/root/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at maybeClose (internal/child_process.js:925)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209)
(anonymous) @ linter-registry.js? [sm]:137
linter-registry.js? [sm]:137 [Linter] Error running Flake8 Error: Traceback (most recent call last):
  File "/usr/bin/flake8", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flake8==3.6.0' distribution was not found and is required by the application
    at ChildProcess.<anonymous> (/root/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at maybeClose (internal/child_process.js:925)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209)
(anonymous) @ linter-registry.js? [sm]:137

**Comment by Arcanemagus** [comment]
> pkg_resources.DistributionNotFound: The 'flake8==3.6.0' distribution was not found and is required by the application

You need to get `flake8` working in the first place before you can use it through this package. Closing this issue to avoid spamming everyone else in this 3 year old issue. If you are still having problems _after_ getting `flake8` itself working please open a new issue @MikeyBrat.
