### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by cyxgun** [AtomLinter/linter-flake8#503]
Getting two tracebacks now:
```pytb
linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc9d' in position 10645: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\obfuscated\AppData\Local\Programs\Python\Python36\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\main\application.py", line 316, in _run
    self.run_checks()
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\main\application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 319, in run
    self.run_serial()
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 303, in run_serial
    checker.run_checks()
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "c:\users\obfuscated\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by Arcanemagus** [comment]
That's an internal `flake8` error. If you run `cat foo.py | flake8 -` you should see the same issue. Report this over on the [flake8 repo](https://gitlab.com/pycqa/flake8) to get it looked at 😉.
