### ISSUE TITLE
[Linter] Error running Flake8

### ISSUE THREAD

**Issue by SalkCoding** [AtomLinter/linter-flake8#591]
"See Console for more info. (Open View -> Developer -> Toggle Developer Tools)" I'm always see this message. and also i'm spend time to solve this problem but i couldn't solve it. what should i do to?

error log
```
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/e904392b5d36452a665527470a5831a9/hover?cursor_runes=194 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\kite.js:598
subs.add.editor.onDidChangeCursorPosition @ C:\Users\josan\.atom\packages\kite\lib\kite-editor.js:66
module.exports.Emitter.simpleDispatch @ <embedded>:66277
module.exports.Emitter.emit @ <embedded>:66393
cursorMoved @ <embedded>:4905
markerDidChange @ <embedded>:37006
Selection.marker.onDidChange.e @ <embedded>:36094
module.exports.Emitter.simpleDispatch @ <embedded>:66277
module.exports.Emitter.emit @ <embedded>:66393
module.exports.DisplayMarker.notifyObservers @ <embedded>:219601
(anonymous) @ <embedded>:219406
module.exports.Emitter.simpleDispatch @ <embedded>:66277
module.exports.Emitter.emit @ <embedded>:66393
module.exports.Marker.emitChangeEvent @ <embedded>:77607
(anonymous) @ <embedded>:77965
module.exports.MarkerLayer.emitChangeEvents @ <embedded>:77962
module.exports.TextBuffer.emitMarkerChangeEvents @ <embedded>:34285
module.exports.TextBuffer.transact @ <embedded>:33532
transact @ <embedded>:4029
mergeIntersectingSelections @ <embedded>:3576
mergeSelections @ <embedded>:5442
mergeIntersectingSelections @ <embedded>:5413
mutateSelectedText @ <embedded>:3575
insertText @ <embedded>:3539
object.(anonymous function) @ <embedded>:17482
didTextInput @ <embedded>:8539
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849 [2018-04-18T14:47:14.944Z] [ERROR] atom-ide-diagnostics - Error in linter provider Flake8: 'flake8'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
Error: 'flake8'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
    at ChildProcess.<anonymous> (C:\Users\josan\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849 [2018-04-18T14:47:14.953Z] [ERROR] atom-error-notification - [Linter] Error running Flake8 (9) [CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite]
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849 [Linter] Error running Flake8 Error: 'flake8'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
    at ChildProcess.<anonymous> (C:\Users\josan\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:194)
    at maybeClose (internal/child_process.js:899)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226)
c.(anonymous function) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849
(anonymous) @ linter-registry.js:137
_tickCallback @ internal/process/next_tick.js:109
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/e904392b5d36452a665527470a5831a9/hover?cursor_runes=194 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setState @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:134
handle403Response @ C:\Users\josan\.atom\packages\kite\lib\kite.js:430
promisifyRequest.then.resp @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:235
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/e904392b5d36452a665527470a5831a9/hover?cursor_runes=194 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setState @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:134
handle403Response @ C:\Users\josan\.atom\packages\kite\lib\kite.js:430
promisifyRequest.then.resp @ C:\Users\josan\.atom\packages\kite\lib\editor-events.js:84
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/e904392b5d36452a665527470a5831a9/hover?cursor_runes=193 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\kite.js:598
subs.add.editor.onDidChangeCursorPosition @ C:\Users\josan\.atom\packages\kite\lib\kite-editor.js:66
module.exports.Emitter.simpleDispatch @ <embedded>:66277
module.exports.Emitter.emit @ <embedded>:66393
cursorMoved @ <embedded>:4905
markerDidChange @ <embedded>:37006
Selection.marker.onDidChange.e @ <embedded>:36094
module.exports.Emitter.simpleDispatch @ <embedded>:66277
module.exports.Emitter.emit @ <embedded>:66393
module.exports.DisplayMarker.notifyObservers @ <embedded>:219601
(anonymous) @ <embedded>:219406
module.exports.Emitter.simpleDispatch @ <embedded>:66277
module.exports.Emitter.emit @ <embedded>:66393
module.exports.Marker.emitChangeEvent @ <embedded>:77607
module.exports.Marker.update @ <embedded>:77540
module.exports.Marker.setHeadPosition @ <embedded>:77315
module.exports.DisplayMarker.setHeadBufferPosition @ <embedded>:219499
module.exports.DisplayMarker.setHeadScreenPosition @ <embedded>:219507
changePosition @ <embedded>:35381
changePosition @ <embedded>:36026
setScreenPosition @ <embedded>:35380
moveLeft @ <embedded>:35601
modifySelection @ <embedded>:36325
modifySelection @ <embedded>:37057
selectLeft @ <embedded>:36325
backspace @ <embedded>:36569
mutateSelectedText.selection @ <embedded>:3563
getSelectionsOrderedByBufferPosition.map @ <embedded>:3577
transact @ <embedded>:3577
module.exports.TextBuffer.transact @ <embedded>:33508
transact @ <embedded>:4029
mergeIntersectingSelections @ <embedded>:3576
mergeSelections @ <embedded>:5442
mergeIntersectingSelections @ <embedded>:5413
mutateSelectedText @ <embedded>:3575
backspace @ <embedded>:3563
object.(anonymous function) @ <embedded>:17482
core:backspace @ <embedded>:20084
(anonymous) @ <embedded>:20343
module.exports.TextBuffer.transact @ <embedded>:33508
transact @ <embedded>:4029
newCommandListeners.(anonymous function) @ <embedded>:20342
handleCommandEvent @ <embedded>:23670
module.exports.KeymapManager.dispatchCommandEvent @ <embedded>:69341
module.exports.KeymapManager.handleKeyboardEvent @ <embedded>:69132
handleDocumentKeyEvent @ <embedded>:19361
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849 [2018-04-18T14:47:15.684Z] [ERROR] atom-ide-diagnostics - Error in linter provider Flake8: 'flake8'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
Error: 'flake8'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
    at ChildProcess.<anonymous> (C:\Users\josan\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849 [2018-04-18T14:47:15.695Z] [ERROR] atom-error-notification - [Linter] Error running Flake8 (8) [CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite]
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849 [Linter] Error running Flake8 Error: 'flake8'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
    at ChildProcess.<anonymous> (C:\Users\josan\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:194)
    at maybeClose (internal/child_process.js:899)
    at Socket.<anonymous> (internal/child_process.js:342)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at Pipe._handle.close [as _onclose] (net.js:510)
c.(anonymous function) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4849
(anonymous) @ linter-registry.js:137
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/86f5fe7a5c90a80ea25b64410472632b/hover?cursor_runes=193 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setState @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:134
handle403Response @ C:\Users\josan\.atom\packages\kite\lib\kite.js:430
promisifyRequest.then.resp @ C:\Users\josan\.atom\packages\kite\lib\editor-events.js:84
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/86f5fe7a5c90a80ea25b64410472632b/hover?cursor_runes=193 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setState @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:134
handle403Response @ C:\Users\josan\.atom\packages\kite\lib\kite.js:430
promisifyRequest.then.resp @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:235
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/86f5fe7a5c90a80ea25b64410472632b/hover?cursor_runes=193 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setState @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:134
handle403Response @ C:\Users\josan\.atom\packages\kite\lib\kite.js:430
promisifyRequest.then.resp @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:47
C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735 GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:josan:Desktop:Programming:Atom:Python:1084.py/86f5fe7a5c90a80ea25b64410472632b/hover?cursor_runes=193 404 (Not Found)
(anonymous) @ C:\Users\josan\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:4735
Promise @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:76
request @ C:\Users\josan\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:46
getHoverDataAtPosition @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:421
setStatusLabel @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:104
setState @ C:\Users\josan\.atom\packages\kite\lib\elements\kite-status.js:134
handle403Response @ C:\Users\josan\.atom\packages\kite\lib\kite.js:430
promisifyRequest.then.resp @ C:\Users\josan\.atom\packages\kite\lib\data-loader.js:47
```

**Comment by SalkCoding** [comment]
@MRossol I'm really appreciate for your help :D
now it's working correctly

**Comment by Arcanemagus** [comment]
You would run that in the terminal/shell/command prompt on your computer.

**Comment by sscswapnil** [comment]
for me also running: py -m pip install flake8 fixed the issue

**Comment by sylviaczha** [comment]
Thank you so much @MRossol and @sscswapnil.
I fixed my problem with: python3 -m pip install flake8.
