### ISSUE TITLE
Flake8 error after install: error importing function defintion for switchml

### ISSUE THREAD

**Issue by clcollins** [AtomLinter/linter-flake8#643]
After install, I received `Error running Flake8` when opening a python file in Atom:

```
[Linter] Error running Flake8 Error: /bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `scl'
/bin/sh: switchml: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `switchml'
    at ChildProcess.<anonymous> (/home/chris/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

Running `flake8` directly on the file works fine.  I tried removing linter and all the linter packages and language packages, and reinstalling just linter and linter-flake8, but continue to receive the error message.  Any assistance would be apprciated.

Thanks!

### System info

*Linter flake8 version*
linter-flake8 v2.3.0

*Atom Version*
```
$ atom --version
Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

*Flake8 version*
```
$ flake8 --version
3.4.1 (flake8-docstrings: 1.3.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.6 on Linux
```

*Python3 version*
```
$ python3 --version
Python 3.6.6
```

*OS version*
```
$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
```

**Comment by clcollins** [comment]
After more searching, I found this: https://github.com/atom/atom/issues/13451

This solved the problem for me, so closing this issue:  not a linter-flake8 problem.

Hopefully Atom or the Fedora package maintainers will fix the issue.
