### ISSUE TITLE
Error in linter-flake8 [URGENT]

### ISSUE THREAD

**Issue by Quantu-Matrix** [AtomLinter/linter-flake8#648]
Every time I type something, it says
'See Console for more info. (Open View -> Developer -> Toggle Developer Tools)'

Upon clicking the 'Toggle Developer Tools,' it showed me these errors.

Unable to locate git workspace root for C:\Users\DELL\Desktop\Python. Expected if C:\Users\DELL\Desktop\Python is not in a git repository. GitError: git rev-parse --show-toplevel in C:\Users\DELL\Desktop\Python exited with code 128
stdout: 
stderr: fatal: not a git repository (or any of the parent directories): .git

    at new GitError (C:\Users\DELL\AppData\Local\atom\app-1.31.2\resources\app\node_modules\github\lib\git-shell-out-strategy.js:123:24)
    at Promise (C:\Users\DELL\AppData\Local\atom\app-1.31.2\resources\app\node_modules\github\lib\git-shell-out-strategy.js:391:29)
    at <anonymous>
revParse @ <embedded>:105865
C:\Users\DELL\.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running Flake8 Error: c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\pycodestyle.py:111: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (C:\Users\DELL\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(anonymous) @ C:\Users\DELL\.atom\packages\linter\lib\linter-registry.js:159
<embedded>:105865 Unable to locate git workspace root for C:\Users\DELL\Desktop\Python\MyFirstProgram.py. Expected if C:\Users\DELL\Desktop\Python\MyFirstProgram.py is not in a git repository. GitError: git rev-parse --show-toplevel in C:\Users\DELL\Desktop\Python exited with code 128
stdout: 
stderr: fatal: not a git repository (or any of the parent directories): .git

    at new GitError (C:\Users\DELL\AppData\Local\atom\app-1.31.2\resources\app\node_modules\github\lib\git-shell-out-strategy.js:123:24)
    at Promise (C:\Users\DELL\AppData\Local\atom\app-1.31.2\resources\app\node_modules\github\lib\git-shell-out-strategy.js:391:29)
    at <anonymous>
revParse @ <embedded>:105865

I am new to programming, so I don't know a thing about that
Greatly appreciated and God Speed.

**Comment by Quantu-Matrix** [comment]
![error_linter-flake8](https://user-images.githubusercontent.com/44132198/46914346-4608e200-cfce-11e8-9f54-ed423ab25e2e.png)
