### ISSUE TITLE
[Lineter] Error running Flake8

### ISSUE THREAD

**Issue by digyx** [AtomLinter/linter-flake8#651]
Installed all dependencies Atom alerted me to, installed flake8, autopep8, and pycodestyle via terminal, and it's giving me this error when I try to run it.  I'm running MacOS, latest updates, already restarted my MacBook.

```
/Users/dtingley/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running Flake8 Error: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2334, in resolve
    raise ImportError(str(exc))
ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.
    at ChildProcess.<anonymous> (/Users/dtingley/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by Arcanemagus** [comment]
It looks like the version of `pycodestyle` you installed isn't compatible with the version of `flake8` you have installed. You'll need to get `flake8` working first before you can use it here 😉.
