### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by aclark73** [AtomLinter/linter-flake8#664]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Code:
from django.views.generic.list import ListView

prior to this, an error message:
flake 8 has crashed
linter-flake8:: Flake8 threw an error related to:
IndexError: list index out of range
Please check Atom's Console for more details

Atom console:
inter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/Applications/Downloaded/anaconda/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/pep8.py", line 1438, in check_all
    self.check_logical()
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/pep8.py", line 1338, in check_logical
    for offset, text in self.run_check(check, argument_names) or ():
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/hacking/checks/python23.py", line 225, in hacking_no_old_style_class
    line = core.import_normalize(logical_line.strip())
  File "/Applications/Downloaded/anaconda/lib/python2.7/site-packages/hacking/core.py", line 105, in import_normalize
    split_line[2] == "import" and split_line[3] != "*" and
IndexError: list index out of range

Debug information:
Atom version: 1.28.1
Flake8 version: `2.5.5 (pep8: 1.5.7, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1, pyflakes: 0.8.1) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
