### ISSUE TITLE
Error running Flake8

### ISSUE THREAD

**Issue by 3nematix** [AtomLinter/linter-flake8#671]
**Hello,**
I did a lot of research before posting this, but many posts from 2018.
I have a problem which i try to fix for hours. So I'm new on Python and Atom Editor. I followed tutorials, how to install packages edit themes.. So after a while i tried to install Flake8, but after i did that when i edit something in my python project, the little red popup appears in the top right. 
It says [Linter] Error running Flake8. I have latest updates of the packages. And i Do get these errors.

Some screenshots:
1. [https://gyazo.com/7e7369138d4716131daa87de8375071a](url)
2. [https://gyazo.com/edb50531beefaaa88126e875c2d330a4](url)
3. [https://gyazo.com/72c9fe0a6f155977f085c33ff668d2c5](url)
I changed the EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[\[({] | [\]}),;:]')
To EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Before
4. [https://gyazo.com/866304f76ace143e91a5451ac4fd16e2](url)
After
5. [https://gyazo.com/f93d966216dcc093443a0ca16cd53178](url)
But i still do have the errors
**ERRORS AFTER CHANGING THE REGEX**
6. [https://gyazo.com/69dfd6606cdcfbcdff5f8e2be3017828](url)

> C:\Users\3Nematic\.atom\packages\linter\lib\linter-registry.js:155 [Linter] Error running Flake8 Error: c:\users\3nematic\appdata\local\programs\python\python37-32\lib\site-packages\pycodestyle.py:111: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (C:\Users\3Nematic\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(anonymous) @ C:\Users\3Nematic\.atom\packages\linter\lib\linter-registry.js:155
>

**Comment by Arcanemagus** [comment]
Also just as an FYI, you can paste images directly in GitHub comments/issues. That way they won't expire when your external hosting service removes them 😉.
