### ISSUE TITLE
Error running flake8 in Atom

### ISSUE THREAD

**Issue by RIPRoyale** [AtomLinter/linter-flake8#708]
I have linter as well as all dependencies installed. But when I startup Atom, I get this error:
C:\Users\hrida\.atom\packages\linter\lib\linter-registry.js:155 [Linter] Error running Flake8 Error: c:\users\hrida\appdata\local\programs\python\python37\lib\site-packages\pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (C:\Users\hrida\.atom\packages\linter-pylint\node_modules\sb-exec\lib\index.js:56:20)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
(anonymous) @ C:\Users\hrida\.atom\packages\linter\lib\linter-registry.js:155

**Comment by AI-Ahmed** [comment]
@RIPRoyale  your problem  will be fixed after following my steps in this link;  [Fix-Linter-flak8](https://github.com/DrStarkXavier/Fix-Linter-flake8).
