### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by dhemanth321** [AtomLinter/linter-flake8#733]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-flake8](https://github.com/AtomLinter/linter-flake8) package 2.4.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at linterFlake8Deps (/packages/linter-flake8/lib/main.js:114:9)
```

### Commands

```
 26x -4:37.6.0 core:backspace (input.hidden-input)
 30x -3:19.9.0 core:move-down (input.hidden-input)
 41x -3:01.6.0 core:move-up (input.hidden-input)
  9x -2:58.6.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
file-icons 2.1.41 
linter-flake8 2.4.0 
minimap 4.29.9 
platformio-ide-terminal 2.10.0 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
script 3.26.0 
```

**Comment by dhemanth321** [comment]
![Uploading Untitled.png…]()
