### ISSUE TITLE
Failed to activate the linter-flake8 package

### ISSUE THREAD

**Issue by JulianGro** [AtomLinter/linter-flake8#767]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. install flake8 on system
2. install linter-flake8 in Atom
3. no profit

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.0-dev-7501657a3 x64
**Electron**: 11.5.0
**OS**: Debian GNU/Linux
**Thrown From**: [linter-flake8](https://github.com/AtomLinter/linter-flake8) package 2.4.0

### Stack Trace

Failed to activate the linter-flake8 package

```
At Cannot find module '../src/babel.config.js'
Require stack:
- /usr/share/atom-dev/resources/app.asar/node_modules/@babel/core/lib/config/files/configuration.js
- /usr/share/atom-dev/resources/app.asar/node_modules/@babel/core/lib/config/files/index.js
- /usr/share/atom-dev/resources/app.asar/node_modules/@babel/core/lib/index.js
- /usr/share/atom-dev/resources/app.asar/static/index.html

Error: Cannot find module '../src/babel.config.js'
Require stack:
- /usr/share/atom-dev/resources/app.asar/node_modules/@babel/core/lib/config/files/configuration.js
- /usr/share/atom-dev/resources/app.asar/node_modules/@babel/core/lib/config/files/index.js
- /usr/share/atom-dev/resources/app.asar/node_modules/@babel/core/lib/index.js
- /usr/share/atom-dev/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at o._resolveFilename (electron/js2c/renderer_init.js:35:917)
    at Function.get_Module._resolveFilename (/usr/share/atom-dev/resources/app/static/<embedded>:11:157942)
    at require.resolve (/usr/share/atom-dev/resources/app/static/<embedded>:11:149312)
    at loadConfig (/app.asar/node_modules/@babel/core/lib/config/files/configuration.js:172:5)
    at loadConfig.next (<anonymous>)
    at buildRootChain (/app.asar/node_modules/@babel/core/lib/config/config-chain.js:80:47)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/app.asar/node_modules/@babel/core/lib/config/partial.js:103:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/app.asar/node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Object.transform (/app.asar/node_modules/@babel/core/lib/transform.js:23:45)
    at transform.next (<anonymous>)
    at evaluateSync (/app.asar/node_modules/gensync/index.js:251:28)
    at Object.sync (/app.asar/node_modules/gensync/index.js:89:14)
    at Object.e.compile (/usr/share/atom-dev/resources/app/static/<embedded>:11:579023)
    at Object.compile (/usr/share/atom-dev/resources/app/static/<embedded>:11:575960)
    at compileFileAtPath (/usr/share/atom-dev/resources/app/static/<embedded>:11:151057)
    at Object.value [as .js] (/usr/share/atom-dev/resources/app/static/<embedded>:11:153473)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at customRequire (/usr/share/atom-dev/resources/app/static/<embedded>:1:756255)
    at requireModule (/usr/share/atom-dev/resources/app/src/atom-environment.js:547:172808)
    at Package.requireMainModule (/usr/share/atom-dev/resources/app/src/atom-environment.js:527:2465701)
    at Package.activateNow (/usr/share/atom-dev/resources/app/src/atom-environment.js:527:2453700)
    at /usr/share/atom-dev/resources/app/src/atom-environment.js:530:2746
```

### Commands

```
```

### Non-Core Packages

```
linter-flake8 2.4.0 
```

### Additional Information

I am using Atom-Community since Atom is being sunset.

**Comment by p-servus** [comment]
i have reported a similar issue here: https://github.com/atom-community/atom/issues/460
.. it is not solved now, but some comments are there .. thx to everyOne who can help to solve it

PS: I was changing from **atom/atom** (AUR) <https://github.com/atom/atom> to **atom-community/atom** (AUR) <https://github.com/atom-community/atom> using Pamac-GUI.
Because:
  > Atom and all repositories under Atom will be archived on December 15, 2022. [official announcement](https://github.blog/2022-06-08-sunsetting-atom/)
