### ISSUE TITLE
Failed to activate the linter-flake8 package

### ISSUE THREAD

**Issue by benjavides** [AtomLinter/linter-flake8#82]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-flake8](https://github.com/AtomLinter/linter-flake8) package, v1.6.1

### Stack Trace

Failed to activate the linter-flake8 package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.provideLinter (C:\Users\Benjamín\.atom\packages\linter-flake8\lib\main.coffee:42:15)
  at Package.module.exports.Package.activateServices (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:416:69)
  at Package.module.exports.Package.activateNow (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:248:16)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:469:29
  at Config.module.exports.Config.transact (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:670:21)
  at Object.<anonymous> (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///C:/Users/Benjam%C3%ADn/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Users/Benjam%C3%ADn/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.4
linter, v1.6.0
linter-flake8, v1.6.1
linter-pep8, v1.0.1
linter-pylint, v1.0.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Can you open a command prompt, switch to the `linter-flake8` directory and run the following:
```
apm install
```

This should ensure that all the dependencies are installed.

**Comment by benjavides** [comment]
Thanks for your help, I went to C:\tools\python\Lib\site-packages\flake8 from the console, then ran `apm install` and this showed:
![capture](https://cloud.githubusercontent.com/assets/7333792/10125169/23569950-6541-11e5-859a-a7636689e1ed.PNG)

**Comment by steelbrain** [comment]
You went to the wrong dir sir :D
it should've been `$HOME/.atom/packages/linter-flake8`

**Comment by benjavides** [comment]
Sorry I´m quite new at this. Ok so I did this:
![1](https://cloud.githubusercontent.com/assets/7333792/10125221/6463447e-6542-11e5-8610-74ccbb15ba9e.PNG)
But then when opening atom this showed:
![2](https://cloud.githubusercontent.com/assets/7333792/10125242/fff347b8-6542-11e5-9961-f931f40df47f.PNG)
So I proceed to do as you told me but with atom-linter, but this happened:
![3](https://cloud.githubusercontent.com/assets/7333792/10125246/26aee0a6-6543-11e5-8a6a-982cf5e9598e.PNG)

**Comment by steelbrain** [comment]
Did you clone these repos or did you install from settings-view?

**Comment by benjavides** [comment]
I ran this commands to install a set of packages:

> pip install --upgrade pylint pep8 flake8
  apm install linter linter-pylint linter-pep8 linter-flake8
  apm install script
  apm install autocomplete-python
  pip install --upgrade autopep8
  apm install atom-beautify

*By mistake I commented this in other issue, sorry*

**Comment by steelbrain** [comment]
Here's my response from that issue
----
that is super-super weird.
On a side note, you can batch apm install commands like
```
apm install atom-beautify linter linter-flake8 linter-pep8 linter-pylint autocomplete-python script
```
and does this help?
```
mv ~/.atom ~/.atom-backup
apm install linter linter-flake8 linter-pep8 linter-pylint
```

**Comment by benjavides** [comment]
I tried that but this showed up:
![4](https://cloud.githubusercontent.com/assets/7333792/10125331/6c4a8bb2-6546-11e5-9fc6-65e79c3359ab.PNG)
(I´m on a administrator account and I run the powershell as administrator)

**Comment by Arcanemagus** [comment]
You could try the full path? But what you typed should work...

**Comment by Arcanemagus** [comment]
Are you behind some sort of proxy?

Just looked around and all 3 of the similar issues are filed by you, which would lead me to think this is an issue unique to your setup and not a new major issue with everyone trying to install `atom-linter` :stuck_out_tongue:.

**Comment by benjavides** [comment]
Yes, I´m also having issues running the `script package`. Everything ran well and suddenly everything stopped working. What´s weird is that I still have the problem after formatting my computer.

**Comment by joaoportela** [comment]
I have the same issue. I believe that you are having issues because of your home folder: like me, you have non-ascii characters in your path.

**Comment by joaoportela** [comment]
@steelbrain thank you very much. :)

**Comment by Arcanemagus** [comment]
@joaoportela if that's the cause of the problem then this is an issue with `apm` or `npm`, since you are able to reproduce this on your machine could you create a user without special characters in the name and see if installation succeeds there?

**Comment by benjavides** [comment]
@joaoportela That was it! I created a new user and everything works well, thank you very much!!

**Comment by Arcanemagus** [comment]
@benjavides Can you file an issue on [`apm`](https://github.com/atom/apm) about this, referencing this issue?

**Comment by benjavides** [comment]
Done. https://github.com/atom/apm/issues/443
