### ISSUE TITLE
Error: Traceback (most recent call last): File "/home/arch/.local/bin/flake8", line 7, in from flake8.main import main ImportError: No module named 'flake8'

### ISSUE THREAD

**Issue by andya9** [AtomLinter/linter-flake8#84]
After updating to 1.7.0 I get this when opening a python file:

Error: Traceback (most recent call last):
  File "/home/arch/.local/bin/flake8", line 7, in <module>
    from flake8.main import main
ImportError: No module named 'flake8'
    at exit (/home/arch/.config/atom/packages/linter-tidy/node_modules/atom-linter/lib/helpers.coffee:32:24)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)

**Comment by andya9** [comment]
My bad, it’s my system: I also upgraded python to 3.5 and it broke my local modules
