### ISSUE TITLE
Value I/O Error

### ISSUE THREAD

**Issue by shipperizer** [AtomLinter/linter-flake8#86]
Since I've updated to python 3.5 I keep getting this:
 
```
Error: Traceback (most recent call last):
  File "/usr/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "/usr/lib/python3.5/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1412, in check_all
    self.check_ast()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1359, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 94, in run
    filename, source = load_file(self.filename)
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 29, in load_file
    return 'stdin', pep8.stdin_get_value()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1060, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file
  at exit (/home/shipperizer/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.coffee:32:24)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

linter-flake8 v1.7.0 and linter v1.8.1
python libs flake8 v2.4.1

**Comment by Arcanemagus** [comment]
This looks like an issue with `flake8`, are you able to run it from the command line?

**Comment by shipperizer** [comment]
Yes without any error(program error):

```
[shipperizer@archer ~]$ flake8 development/portal/manage.py 
development/portal/manage.py:1:1: D100  Missing docstring in public module
development/portal/manage.py:1:1: D100 Missing docstring in public module
development/portal/manage.py:2:1: H306  imports not in alphabetical order (flask.url_for, flask.ext.script.manager)
development/portal/manage.py:12:1: D103  Missing docstring in public function
development/portal/manage.py:12:1: D103 Missing docstring in public function
development/portal/manage.py:
```

**Comment by Arcanemagus** [comment]
Can you explicitly specify the _full_ path to `flake8` in the Settings? I'm wondering if you have multiple installed and it's picking the wrong one.

**Comment by shipperizer** [comment]
from config.cson
```  
"linter-flake8":
    maxLineLength: 100
    executablePath: "/usr/bin/flake8"
```
and from the shell 
```
[shipperizer@archer ~]$ which flake8
/usr/bin/flake8
```

**Comment by Arcanemagus** [comment]
The python trace points to their `stdin` handling path, maybe something about that is broken? Can you try piping the file into `flake8`?

```
cat /path/to/file | flake8 -
```

**Comment by shipperizer** [comment]
Something weird, just happened...i was changing my code and I was missing a ) but the flake8 plugin worked as expected, I added it back and It got broken again....no idea

anyway:
```log
[shipperizer@archer user-service]$ cat /home/shipperizer/development/portal/manage.py | flake8 -
Traceback (most recent call last):
  File "/usr/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "/usr/lib/python3.5/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1412, in check_all
    self.check_ast()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1359, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 94, in run
    filename, source = load_file(self.filename)
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 29, in load_file
    return 'stdin', pep8.stdin_get_value()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1060, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file
```
this happens with all the files

**Comment by shipperizer** [comment]
hold on:
```bash
[shipperizer@archer portal]$ source env/bin/activate
(env) [shipperizer@archer portal]$ cat /home/shipperizer/development/portal/manage.py | flake8 -
stdin:23:80: E501 line too long (91 > 79 characters)
```
is the fact that I have the code inside a virtualenv generating issues with this?

**Comment by Arcanemagus** [comment]
If you are using `virtualenv` you need to activate it first, and then launch Atom from within that environment for it to get the proper setup (see [the readme](https://github.com/AtomLinter/linter-flake8#virtualenv)).

However, that being said, if `flake8` is crashing on the command line when you don't have the `virtualenv` enabled it sounds like there is an issue with `flake8` itself in play here as well. You might want to file an issue [over there](https://gitlab.com/pycqa/flake8/issues).

Let me know how that goes for you!

**Comment by shipperizer** [comment]
got it working using activating virtualenv and launching atom from the cmd line, it's thou a bit annoying as I can't use my "shiny Icon" to launch it....opened https://gitlab.com/pycqa/flake8/issues/92, feel free to jump in if you have anything to add

**Comment by shipperizer** [comment]
ok, so after the response of @sigmavirus24:
```
Please look closely at your stack trace: This is coming from the flake8-pep257 plugin that you're using.

  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 94, in run
    filename, source = load_file(self.filename)
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 29, in load_file
    return 'stdin', pep8.stdin_get_value()
We can't do very much to help you when plugins are broken.

I suspect that your virtual environment doesn't have that plugin installed and that's why this works.
```
i uninstalled flake8_pep257, first from the virtualenv and then globally, now it works in any case even without launching it from the shell with the venv set

**Comment by Arcanemagus** [comment]
You can try the `flake8-docstrings` alternative, but I have had better luck personally with `flake8-pep257`. I'm sure the author of that would like a bug report [over here](https://github.com/Robpol86/flake8-pep257/issues) so this can be fixed there though :wink:.

As this isn't an issue with `linter-flake8` I'm going to mark this as closed. I would be interested in any further developments though.

**Comment by Arcanemagus** [comment]
Actually, looks like it's already been filed here: https://github.com/Robpol86/flake8-pep257/issues/2
